### ISSUE TITLE
[BUG] DNS didn't change for LTE/WI-FI

### ISSUE THREAD

**Issue by bzz11g** [DedBash/Magisk-DNS-Servers#1]
DNS didn't change after applying Magisk module
I check Google, OpenDNS, Uncensored
all for IPv4

 - Device: Pixel 6
 - Android 13 build TQ1A.230105.002 (January stable)
 - Magisk 25206 (latest canary)

I perform phone reboot after every install/uninstall module in Magisk
I check my DNS with [Network Analyzer Pro](https://play.google.com/store/apps/details?id=net.techet.netanalyzer.an) app and every time i these DNS servers:
LTE
10.97.52.68
10.97.52.77
WI-FI
192.168.1.1 (local network)
![Screenshot_20230110-155823](https://user-images.githubusercontent.com/1549909/211559805-1bf8cdf3-55b1-4891-a678-16101ced3954.png)
![Screenshot_20230110-155859](https://user-images.githubusercontent.com/1549909/211559810-9a7e08b1-6c85-4ee0-a987-e0e5f606c2be.png)

I can provide more information and logs if you need something else, also I can perform tests in short time, thank you

**Comment by DedBash** [comment]
!!EDIT!!
Yes the app time something like that also at me but that is also not quite true
APP output:
![Screenshot_20230117-124340](https://user-images.githubusercontent.com/79027536/212890905-4cd5bce9-208f-4bf0-8ea4-60703e45efa2.png)
The entered actual DNS enrollees:
![Screenshot_20230117-124352](https://user-images.githubusercontent.com/79027536/212891110-13ee7b8d-fdaa-4f43-b237-217662fa25ab.png)
And also https://www.dnsleaktest.com/ recognizes adguard:
![Screenshot_20230117-124415](https://user-images.githubusercontent.com/79027536/212891271-03f19e4c-e56e-4f70-a6a6-40d2346e6e0a.png)
But I can say that the app shows the DNS servers that my router gives and in this there are no modified DNS in it (that use adguard or similar).

**Comment by bzz11g** [comment]
i will check this out tomorrow, thank you for information

**Comment by bzz11g** [comment]
Yes, i can confirm that Network Analyzer Pro and some other similar apps showing wrong information about DNS
all working good
