### ISSUE TITLE
[Submit DNS] 

### ISSUE THREAD

**Issue by coxchris502** [DedBash/Magisk-DNS-Servers#3]
**Name and a link to the DNS provider**
Nextdns 
https://Nextdns.io

**Check beforehand that the DNS provider has IPv6 support.**
yes provider supports IPv6.

**Comment by DedBash** [comment]
@coxchris502 
I have now added the NextDNS module but have not yet fully tested it, if you notice any errors please let me know

https://github.com/DedBash/Magisk-DNS-Servers/releases/download/Upload_All_v102/NextDNS4Magisk.zip

**Comment by cipitaua** [comment]
Hi,

in NextDNS it is fundamental to associate the account to the dns call. This can be done in two ways. First, by associating the ip address with the nextdns account, but this would not work for mobile connections where the ip changes frequently.
Second, using the 'private dns' feature of android, by prepending the NextDNS account id to the dns resolver url, e.g.:

5c9d8e.dns.nextdns.io

Conveniently, it is also possible to pass the device name by prepending a further string:

 John--phone-5c9d8e.dns.nextdns.io

Unfortunately, all the above is not possible using plain dns ip, such as 45.90.28.206.

Would it be possible to force some private dns through magisk? I think this would be the only way to make the most of NextDNS (e.g. for parental control).
